
language: python
python:
  - "3.5"

env:
  global:
  - TRAVIS_TAG="$(date -u '+%d.%m.%y-%H.%M')"

branches:
  only:
  - master

script:
  python ./tools/export_mod.py

before_deploy:
  sh ./tools/deploy.sh

notifications:
  slack: sbtrus:4Oz4NTrFDcOeFhG2WKGzYMc3

deploy:
  provider: releases
  api_key: "$AUTH_TOKEN"
  file: 
    - "Russian.zip"
  skip_cleanup: true
  on:
    branch: master
